# .github/workflows/ci.yml

name: C++ CI with Conan, CMake, and CPack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-package:
    name: ${{ matrix.os }} - ${{ matrix.build_type }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
      # 步骤 1-5 保持不变...
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install CPack Generators
        if: matrix.build_type == 'Release' && runner.os == 'Windows'
        run: choco install nsis

      - name: Setup Python for Conan
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Conan and create default profile
        run: |
          pip install conan
          conan profile detect --force

      - name: Cache Conan packages
        uses: actions/cache@v4
        with:
          path: ~/.conan2/p
          key: conan-${{ runner.os }}-${{ matrix.build_type }}-${{ hashFiles('**/conanfile.py') }}
          restore-keys: |
            conan-${{ runner.os }}-${{ matrix.build_type }}-

      - name: Install dependencies with Conan
        run: conan install . --build=missing -s build_type=${{ matrix.build_type }}

      - name: Set lowercase build type
        id: build_type_lc
        run: echo "value=$(echo "${{ matrix.build_type }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
        shell: bash

      # (!!!) 步骤 6: 平台感知的 CMake 配置 (!!!)
      - name: Configure CMake
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            # Windows 使用 'conan-default' preset
            cmake --preset conan-default -DBUILD_TESTING=ON
          else
            # Linux/macOS 使用 'conan-debug' 或 'conan-release'
            cmake --preset conan-${{ steps.build_type_lc.outputs.value }} -DBUILD_TESTING=ON
          fi

      # (!!!) 步骤 7: 平台感知的 CMake 构建 (!!!)
      - name: Build project with CMake
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            # Windows (多配置) 必须在构建时通过 --config 指定配置
            cmake --build --preset conan-default --config ${{ matrix.build_type }}
          else
            # Linux/macOS (单配置) 的配置已在 preset 中确定
            cmake --build --preset conan-${{ steps.build_type_lc.outputs.value }}
          fi

      # (!!!) 步骤 8: 平台感知的单元测试 (!!!)
      - name: Run Unit Tests with CTest
        if: matrix.build_type == 'Debug'
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            # Windows CTest 同样需要 -C 来指定要测试的配置
            ctest --preset conan-default -C Debug
          else
            ctest --preset conan-debug
          fi

      # (!!!) 步骤 9: 平台感知的打包 (!!!)
      - name: Create package with CPack
        if: matrix.build_type == 'Release'
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            # Windows 打包也需要指定配置
            cmake --build --preset conan-default --config Release --target package
          else
            cmake --build --preset conan-release --target package
          fi

      # 步骤 10: 上传产物 - 无需改动
      - name: Upload Build Artifacts
        if: matrix.build_type == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: myproject-package-${{ matrix.os }}
          path: |
            build/Release/
            build/
            *.deb
            *.rpm
            *.exe
            *.zip
            *.tar.gz
          if-no-files-found: ignore